# Conexão (USE SEUS DADOS REAIS)
spring.datasource.url=jdbc:postgresql://localhost:5432/curriculo_db
spring.datasource.username=postgres
spring.datasource.password=admin123

# Configurações críticas do Hibernate
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

# Logs detalhados
logging.level.org.hibernate=DEBUG
logging.level.org.springframework.jdbc=TRACE